### ISSUE TITLE
install too many url will throw error

### ISSUE THREAD

**Issue by ahaoboy** [easy-install/easy-setup#1]
https://github.com/easy-install/easy-setup/actions/runs/13363553378/job/37317193214

```
node:internal/deps/undici/undici:13185
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at async V (/home/runner/work/easy-setup/easy-setup/bundle/action.js:6:1190)
    at async A.getManfiest (/home/runner/work/easy-setup/easy-setup/bundle/action.js:6:3599)
    at async HI (/home/runner/work/easy-setup/easy-setup/bundle/action.js:6:8999)
    at async tg (/home/runner/work/easy-setup/easy-setup/bundle/action.js:6:9995) {
  [cause]: SocketError: other side closed
      at TLSSocket.<anonymous> (node:internal/deps/undici/undici:[60](https://github.com/easy-install/easy-setup/actions/runs/13363553378/job/37317193214#step:10:61)40:28)
      at TLSSocket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '10.1.0.186',
      localPort: 57734,
      remoteAddress: '140.82.113.3',
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 5872,
      bytesRead: 73[64](https://github.com/easy-install/easy-setup/actions/runs/13363553378/job/37317193214#step:10:65)1
    }
  }
}

Node.js v20.18.0
```

```
      - name: url list
        uses: ./
        with:
          url: |-
              https://github.com/ahaoboy/txiki.js-build
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/llrt.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/fnm.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/node.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/bun.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/boa.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/hermes.json
              https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/xst.json
          # FIXME: too many url will throw error
          # url: |-
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/node.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/bun.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/boa.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/llrt.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/hermes.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/xst.json
          #   https://github.com/denoland/deno
          #   https://github.com/ahaoboy/txiki.js-build
          #   https://github.com/ahaoboy/spidermonkey-build
          #   https://github.com/ahaoboy/v8-build
          #   https://github.com/ahaoboy/jsc-build
          #   https://github.com/ahaoboy/jerryscript-build
          #   https://github.com/ahaoboy/mujs-build
          #   https://github.com/axodotdev/cargo-dist
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/llrt.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/fnm.json
          #   https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/bun.json

```
